# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
      with:
        version: 10.x
    
    - name: Install yarn
      run: curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.0

    - name: Install dependencies
      run: yarn install
    
    - name: Build
      run: yarn build
    
    - name: Test
      run: yarn test
    
    
